name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  install_conan:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - macos-13
          - macos-14
          - macos-15
          - windows-2022
          - windows-11-arm

    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'       
      - uses: actions/checkout@v5
        with:
          submodules: true
      - run: npm install
      - run: npx xpm install
      - run: npx xpm run build
      - name: Test
        run: npx xpm run test
